version: 2

docker_build: &docker_build
   command: |
     docker build . -t $SERVICE_NAME:$COMMIT
     docker tag $SERVICE_NAME:$COMMIT $DOCKER_ORG/$SERVICE_NAME:$DOCKER_TAG
     if [ "$PUSH_GIT_COMMIT" = true ] ; then \
       docker tag $SERVICE_NAME:$COMMIT $DOCKER_ORG/$SERVICE_NAME:$COMMIT; \
     fi
     if [ "$PUSH_GIT_TAG" = true ] && [ -n "$CIRCLE_TAG" ] ; then \
       docker tag $SERVICE_NAME:$COMMIT $DOCKER_ORG/$SERVICE_NAME:$(echo "$COMMIT_TAG" | cut -c 2-); \
     fi
     docker push $DOCKER_ORG/$SERVICE_NAME

# Common steps for building client Docker image
build_steps: &build_steps
  docker:
    - image: circleci/node:9.2.0

  steps:
    - checkout

    - setup_remote_docker

    - run:
        name: Set COMMIT env var
        command: echo 'export COMMIT=${CIRCLE_SHA1::8}' >> $BASH_ENV

    - run:
        name: Sign in to Docker Hub
        command: docker login -u $DOCKER_ID -p $DOCKER_PASSWORD

    - run:
        name: Build and push web service
        environment:
          SERVICE_NAME: metagenscope-client
          NODE_ENV: production
        <<: *docker_build


# CircleCI Jobs
jobs:
  run_tests:
    docker:
      - image: circleci/node:9.2.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install node dependencies
          command: npm install --silent

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint client
          command: npm run lint

  test_build:
    docker:
      - image: circleci/node:9.2.0

    environment:
      TAG: test

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Set COMMIT env var
          command: echo 'export COMMIT=${CIRCLE_SHA1::8}' >> $BASH_ENV

      - run:
          name: Build web service
          environment:
            CLIENT_SERVICE: metagenscope-client
            NODE_ENV: production
          command: |
            docker build . -t $CLIENT_SERVICE:$COMMIT

  build_staging:
    <<: *build_steps
    environment:
      DOCKER_TAG: staging
      DOCKER_ORG: metagenscope
      PUSH_GIT_COMMIT: true
      PUSH_GIT_TAG: false

  deploy_staging:
    docker:
      - image: circleci/node:9.2.0

    working_directory: ~/repo

    steps:
      - run:
          name: Deploy to emptyfish.net
          command: |
            set -x
            echo "$STAGING_MACHINE_IP $STAGING_MACHINE_HOST_KEY" > ~/tmp_auth_hosts
            ssh -A -o "UserKnownHostsFile ~/tmp_auth_hosts" $STAGING_MACHINE_USER@$STAGING_MACHINE_IP "cd /home/metagenscope/metagenscope-app && sh deploy.sh"

  build_release:
    <<: *build_steps
    environment:
      DOCKER_TAG: latest
      DOCKER_ORG: metagenscope
      PUSH_GIT_COMMIT: false
      PUSH_GIT_TAG: true


# CircleCI Workflows
workflows:
  version: 2

  test-and-deploy:
    jobs:
      - run_tests:
            context: metagenscope-staging
      - test_build:
          context: metagenscope-staging
          filters:
            branches:
              ignore:
                - develop
                - master
          requires:
            - run_tests
      - build_staging:
          context: metagenscope-staging
          filters:
            branches:
              only: develop
          requires:
            - run_tests
      - deploy_staging:
          context: metagenscope-staging
          filters:
            branches:
              only: develop
          requires:
            - build_staging
      - build_release:
          context: metagenscope-staging
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - run_tests
