version: 2

# CircleCI Jobs
jobs:
  lint:
    docker:
      - image: circleci/node:12.16.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install node dependencies
          command: yarn install --silent

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install typings dependencies
          command: ./node_modules/.bin/typings install

      - run:
          name: Lint commits
          command: yarn commitlint-circle

      - run:
          name: Lint client
          command: yarn lint:report

# CircleCI Workflows
workflows:
  version: 2

  test:
    jobs:
      - lint
